# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OsrmTools
                                 A QGIS plugin
 Plugin to use OSRM API in Qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-24
        copyright            : (C) 2018 by Matthieu Viry
        email                : matthieu.viry@cnrs.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OsrmTools class from file OsrmTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .osrm import OsrmTools
    return OsrmTools(iface)
