# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'osrm_route_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OsrmRouteDialog(object):
    def setupUi(self, OsrmRouteDialog):
        OsrmRouteDialog.setObjectName("OsrmRouteDialog")
        OsrmRouteDialog.resize(453, 461)
        self.label_subtitle = QtWidgets.QLabel(OsrmRouteDialog)
        self.label_subtitle.setGeometry(QtCore.QRect(80, 10, 281, 20))
        self.label_subtitle.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_subtitle.setFont(font)
        self.label_subtitle.setObjectName("label_subtitle")
        self.label_3 = QtWidgets.QLabel(OsrmRouteDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 251, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(OsrmRouteDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 250, 388, 169))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonClear = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.gridLayout.addWidget(self.pushButtonClear, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButtonTryIt = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTryIt.setFont(font)
        self.pushButtonTryIt.setObjectName("pushButtonTryIt")
        self.gridLayout.addWidget(self.pushButtonTryIt, 6, 0, 1, 1)
        self.checkBox_alternative = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_alternative.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(False)
        self.checkBox_alternative.setFont(font)
        self.checkBox_alternative.setObjectName("checkBox_alternative")
        self.gridLayout.addWidget(self.checkBox_alternative, 1, 0, 1, 1)
        self.pushButtonReverse = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonReverse.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButtonReverse.setFont(font)
        self.pushButtonReverse.setObjectName("pushButtonReverse")
        self.gridLayout.addWidget(self.pushButtonReverse, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_about = QtWidgets.QPushButton(OsrmRouteDialog)
        self.pushButton_about.setGeometry(QtCore.QRect(10, 430, 85, 27))
        self.pushButton_about.setObjectName("pushButton_about")
        self.close_button_box = QtWidgets.QDialogButtonBox(OsrmRouteDialog)
        self.close_button_box.setGeometry(QtCore.QRect(260, 430, 176, 27))
        self.close_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.close_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.close_button_box.setObjectName("close_button_box")
        self.label = QtWidgets.QLabel(OsrmRouteDialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 120, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(OsrmRouteDialog)
        self.label_2.setGeometry(QtCore.QRect(161, 60, 234, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layoutWidget1 = QtWidgets.QWidget(OsrmRouteDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 80, 411, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonOrigin = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.pushButtonOrigin.setFont(font)
        self.pushButtonOrigin.setObjectName("pushButtonOrigin")
        self.gridLayout_2.addWidget(self.pushButtonOrigin, 0, 0, 1, 1)
        self.lineEdit_xyO = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_xyO.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_xyO.setFont(font)
        self.lineEdit_xyO.setObjectName("lineEdit_xyO")
        self.gridLayout_2.addWidget(self.lineEdit_xyO, 0, 2, 1, 1)
        self.pushButtonDest = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.pushButtonDest.setFont(font)
        self.pushButtonDest.setObjectName("pushButtonDest")
        self.gridLayout_2.addWidget(self.pushButtonDest, 2, 0, 1, 1)
        self.lineEdit_xyD = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_xyD.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_xyD.setFont(font)
        self.lineEdit_xyD.setObjectName("lineEdit_xyD")
        self.gridLayout_2.addWidget(self.lineEdit_xyD, 2, 2, 1, 1)
        self.labem_host = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.labem_host.setFont(font)
        self.labem_host.setObjectName("labem_host")
        self.gridLayout_2.addWidget(self.labem_host, 3, 0, 1, 1)
        self.lineEdit_host = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.gridLayout_2.addWidget(self.lineEdit_host, 3, 2, 1, 1)
        self.pushButtonIntermediate = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        self.pushButtonIntermediate.setFont(font)
        self.pushButtonIntermediate.setObjectName("pushButtonIntermediate")
        self.gridLayout_2.addWidget(self.pushButtonIntermediate, 1, 0, 1, 1)
        self.lineEdit_xyI = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_xyI.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_xyI.setFont(font)
        self.lineEdit_xyI.setObjectName("lineEdit_xyI")
        self.gridLayout_2.addWidget(self.lineEdit_xyI, 1, 2, 1, 1)
        self.lineEdit_profileName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_profileName.setObjectName("lineEdit_profileName")
        self.gridLayout_2.addWidget(self.lineEdit_profileName, 4, 2, 1, 1)
        self.labem_profile = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.labem_profile.setFont(font)
        self.labem_profile.setObjectName("labem_profile")
        self.gridLayout_2.addWidget(self.labem_profile, 4, 0, 1, 1)
        self.label_2.raise_()
        self.label.raise_()
        self.pushButton_about.raise_()
        self.close_button_box.raise_()
        self.label_subtitle.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_3.raise_()

        self.retranslateUi(OsrmRouteDialog)
        self.close_button_box.accepted.connect(OsrmRouteDialog.accept)
        self.close_button_box.rejected.connect(OsrmRouteDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OsrmRouteDialog)

    def retranslateUi(self, OsrmRouteDialog):
        _translate = QtCore.QCoreApplication.translate
        OsrmRouteDialog.setWindowTitle(_translate("OsrmRouteDialog", "OSRM"))
        self.label_subtitle.setToolTip(_translate("OsrmRouteDialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_subtitle.setText(_translate("OsrmRouteDialog", "<html><head/><body><p align=\"center\">Get the fastest route with OSRM</p></body></html>"))
        self.label_3.setText(_translate("OsrmRouteDialog", "Select the origin and the destination : "))
        self.pushButtonClear.setText(_translate("OsrmRouteDialog", "Clear previous routes"))
        self.pushButtonTryIt.setText(_translate("OsrmRouteDialog", "Display the result"))
        self.checkBox_alternative.setText(_translate("OsrmRouteDialog", "Display possible alternatives roads"))
        self.pushButtonReverse.setText(_translate("OsrmRouteDialog", "Reverse O/D"))
        self.pushButton_about.setText(_translate("OsrmRouteDialog", "About.."))
        self.label.setText(_translate("OsrmRouteDialog", "- clicking on the map :"))
        self.label_2.setText(_translate("OsrmRouteDialog", "- with two tuples of (long.,lat.) coordinates :"))
        self.pushButtonOrigin.setText(_translate("OsrmRouteDialog", "Origin point"))
        self.pushButtonDest.setText(_translate("OsrmRouteDialog", "Destination point"))
        self.labem_host.setText(_translate("OsrmRouteDialog", "<html><head/><body><p align=\"center\">OSRM instance url</p></body></html>"))
        self.lineEdit_host.setText(_translate("OsrmRouteDialog", "http://127.0.0.1:5000/"))
        self.pushButtonIntermediate.setText(_translate("OsrmRouteDialog", "Intermadiate point(s)"))
        self.lineEdit_profileName.setText(_translate("OsrmRouteDialog", "v1/driving"))
        self.labem_profile.setText(_translate("OsrmRouteDialog", "<html><head/><body><p align=\"center\">Profile name</p></body></html>"))

