# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'osrm_table_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OsrmTableDialog(object):
    def setupUi(self, OsrmTableDialog):
        OsrmTableDialog.setObjectName("OsrmTableDialog")
        OsrmTableDialog.resize(514, 498)
        self.pushButton_fetch = QtWidgets.QPushButton(OsrmTableDialog)
        self.pushButton_fetch.setGeometry(QtCore.QRect(170, 460, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_fetch.setFont(font)
        self.pushButton_fetch.setObjectName("pushButton_fetch")
        self.pushButton_about = QtWidgets.QPushButton(OsrmTableDialog)
        self.pushButton_about.setGeometry(QtCore.QRect(10, 460, 85, 27))
        self.pushButton_about.setObjectName("pushButton_about")
        self.close_button_box = QtWidgets.QDialogButtonBox(OsrmTableDialog)
        self.close_button_box.setGeometry(QtCore.QRect(410, 460, 91, 27))
        self.close_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.close_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.close_button_box.setObjectName("close_button_box")
        self.layoutWidget = QtWidgets.QWidget(OsrmTableDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 471, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_subtitle = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_subtitle.setFont(font)
        self.label_subtitle.setObjectName("label_subtitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_subtitle)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_layer = gui.QgsMapLayerComboBox(self.layoutWidget)
        self.comboBox_layer.setObjectName("comboBox_layer")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_layer)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_idfield = gui.QgsFieldComboBox(self.layoutWidget)
        self.comboBox_idfield.setObjectName("comboBox_idfield")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_idfield)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_layer_2 = gui.QgsMapLayerComboBox(self.layoutWidget)
        self.comboBox_layer_2.setObjectName("comboBox_layer_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_layer_2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_idfield_2 = gui.QgsFieldComboBox(self.layoutWidget)
        self.comboBox_idfield_2.setObjectName("comboBox_idfield_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_idfield_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.labem_host = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.labem_host.setFont(font)
        self.labem_host.setObjectName("labem_host")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labem_host)
        self.lineEdit_host = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_host)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_profileName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_profileName.setFont(font)
        self.lineEdit_profileName.setObjectName("lineEdit_profileName")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_profileName)
        self.checkBox_minutes = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setItalic(False)
        self.checkBox_minutes.setFont(font)
        self.checkBox_minutes.setObjectName("checkBox_minutes")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.checkBox_minutes)
        self.checkBox_flatten = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.checkBox_flatten.setFont(font)
        self.checkBox_flatten.setObjectName("checkBox_flatten")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.checkBox_flatten)
        self.checkBox_empty_val = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_empty_val.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.checkBox_empty_val.setFont(font)
        self.checkBox_empty_val.setObjectName("checkBox_empty_val")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.checkBox_empty_val)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.pushButton_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_browse.setAutoDefault(True)
        self.pushButton_browse.setDefault(False)
        self.pushButton_browse.setFlat(False)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.pushButton_browse)
        self.lineEdit_output = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_output.setText("")
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.lineEdit_output)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.pushButton_about.raise_()
        self.close_button_box.raise_()
        self.layoutWidget.raise_()
        self.pushButton_fetch.raise_()

        self.retranslateUi(OsrmTableDialog)
        self.close_button_box.accepted.connect(OsrmTableDialog.accept)
        self.close_button_box.rejected.connect(OsrmTableDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OsrmTableDialog)

    def retranslateUi(self, OsrmTableDialog):
        _translate = QtCore.QCoreApplication.translate
        OsrmTableDialog.setWindowTitle(_translate("OsrmTableDialog", "OSRM"))
        self.pushButton_fetch.setText(_translate("OsrmTableDialog", "Fetch the result"))
        self.pushButton_about.setText(_translate("OsrmTableDialog", "About.."))
        self.label_subtitle.setToolTip(_translate("OsrmTableDialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_subtitle.setText(_translate("OsrmTableDialog", "<html><head/><body><p align=\"center\">Get a time-distance matrix with OSRM</p></body></html>"))
        self.label_3.setText(_translate("OsrmTableDialog", "Source point layer"))
        self.label_5.setText(_translate("OsrmTableDialog", "ID field"))
        self.label_6.setText(_translate("OsrmTableDialog", "Destination point layer"))
        self.label_7.setText(_translate("OsrmTableDialog", "ID field"))
        self.labem_host.setText(_translate("OsrmTableDialog", "Host"))
        self.lineEdit_host.setText(_translate("OsrmTableDialog", "http://127.0.0.1:5000/"))
        self.label.setText(_translate("OsrmTableDialog", "Profile name"))
        self.lineEdit_profileName.setText(_translate("OsrmTableDialog", "v1/driving"))
        self.checkBox_minutes.setText(_translate("OsrmTableDialog", "Time converted in minutes"))
        self.checkBox_flatten.setText(_translate("OsrmTableDialog", "Flatten the matrix "))
        self.checkBox_empty_val.setText(_translate("OsrmTableDialog", "Put an empty value for not found connection"))
        self.label_4.setText(_translate("OsrmTableDialog", "Output .csv table :"))
        self.pushButton_browse.setText(_translate("OsrmTableDialog", "Browse"))

from qgis import gui
