# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'osrm_batch_route_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OsrmBatchRouteDialog(object):
    def setupUi(self, OsrmBatchRouteDialog):
        OsrmBatchRouteDialog.setObjectName("OsrmBatchRouteDialog")
        OsrmBatchRouteDialog.resize(450, 500)
        self.label_subtitle = QtWidgets.QLabel(OsrmBatchRouteDialog)
        self.label_subtitle.setGeometry(QtCore.QRect(80, 10, 281, 20))
        self.label_subtitle.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_subtitle.setFont(font)
        self.label_subtitle.setObjectName("label_subtitle")
        self.layoutWidget = QtWidgets.QWidget(OsrmBatchRouteDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 370, 391, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonRun = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRun.setFont(font)
        self.pushButtonRun.setObjectName("pushButtonRun")
        self.gridLayout.addWidget(self.pushButtonRun, 2, 0, 1, 1)
        self.pushButtonReverse = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonReverse.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setKerning(True)
        self.pushButtonReverse.setFont(font)
        self.pushButtonReverse.setDefault(False)
        self.pushButtonReverse.setFlat(False)
        self.pushButtonReverse.setObjectName("pushButtonReverse")
        self.gridLayout.addWidget(self.pushButtonReverse, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.check_add_layer = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_add_layer.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.check_add_layer.setFont(font)
        self.check_add_layer.setAutoFillBackground(False)
        self.check_add_layer.setChecked(True)
        self.check_add_layer.setObjectName("check_add_layer")
        self.gridLayout.addWidget(self.check_add_layer, 0, 0, 1, 1)
        self.pushButton_about = QtWidgets.QPushButton(OsrmBatchRouteDialog)
        self.pushButton_about.setGeometry(QtCore.QRect(10, 470, 85, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_about.setFont(font)
        self.pushButton_about.setObjectName("pushButton_about")
        self.close_button_box = QtWidgets.QDialogButtonBox(OsrmBatchRouteDialog)
        self.close_button_box.setGeometry(QtCore.QRect(335, 470, 101, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.close_button_box.setFont(font)
        self.close_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.close_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.close_button_box.setObjectName("close_button_box")
        self.FieldOriginX = gui.QgsFieldComboBox(OsrmBatchRouteDialog)
        self.FieldOriginX.setEnabled(False)
        self.FieldOriginX.setGeometry(QtCore.QRect(70, 207, 151, 20))
        self.FieldOriginX.setObjectName("FieldOriginX")
        self.FieldOriginY = gui.QgsFieldComboBox(OsrmBatchRouteDialog)
        self.FieldOriginY.setEnabled(False)
        self.FieldOriginY.setGeometry(QtCore.QRect(70, 230, 151, 20))
        self.FieldOriginY.setObjectName("FieldOriginY")
        self.FieldDestinationX = gui.QgsFieldComboBox(OsrmBatchRouteDialog)
        self.FieldDestinationX.setEnabled(False)
        self.FieldDestinationX.setGeometry(QtCore.QRect(230, 207, 151, 20))
        self.FieldDestinationX.setObjectName("FieldDestinationX")
        self.FieldDestinationY = gui.QgsFieldComboBox(OsrmBatchRouteDialog)
        self.FieldDestinationY.setEnabled(False)
        self.FieldDestinationY.setGeometry(QtCore.QRect(230, 230, 151, 20))
        self.FieldDestinationY.setObjectName("FieldDestinationY")
        self.label_6 = QtWidgets.QLabel(OsrmBatchRouteDialog)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(80, 190, 131, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(OsrmBatchRouteDialog)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(240, 190, 131, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(OsrmBatchRouteDialog)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(30, 210, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(OsrmBatchRouteDialog)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(30, 230, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(OsrmBatchRouteDialog)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(10, 250, 431, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(OsrmBatchRouteDialog)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 431, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.splitter = QtWidgets.QSplitter(OsrmBatchRouteDialog)
        self.splitter.setEnabled(True)
        self.splitter.setGeometry(QtCore.QRect(50, 160, 301, 27))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.ComboBoxCsv = gui.QgsMapLayerComboBox(self.splitter)
        self.ComboBoxCsv.setEnabled(False)
        self.ComboBoxCsv.setObjectName("ComboBoxCsv")
        self.layoutWidget1 = QtWidgets.QWidget(OsrmBatchRouteDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 264, 391, 93))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonBrowse = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonBrowse.setFont(font)
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.gridLayout_3.addWidget(self.pushButtonBrowse, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.lineEdit_output = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_output.setText("")
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.gridLayout_3.addWidget(self.lineEdit_output, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_profileName = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_profileName.setFont(font)
        self.lineEdit_profileName.setObjectName("lineEdit_profileName")
        self.gridLayout_3.addWidget(self.lineEdit_profileName, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_host = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_host.setObjectName("comboBox_host")
        self.comboBox_host.addItem("")
        self.comboBox_host.addItem("")
        self.comboBox_host.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_host, 0, 1, 1, 2)
        self.frame_pts_layer = QtWidgets.QFrame(OsrmBatchRouteDialog)
        self.frame_pts_layer.setEnabled(True)
        self.frame_pts_layer.setGeometry(QtCore.QRect(30, 90, 391, 49))
        self.frame_pts_layer.setObjectName("frame_pts_layer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_pts_layer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_pts_layer)
        self.label_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.ComboBoxDestination = gui.QgsMapLayerComboBox(self.frame_pts_layer)
        self.ComboBoxDestination.setEnabled(False)
        self.ComboBoxDestination.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ComboBoxDestination.setFont(font)
        self.ComboBoxDestination.setObjectName("ComboBoxDestination")
        self.gridLayout_2.addWidget(self.ComboBoxDestination, 1, 1, 1, 1)
        self.ComboBoxOrigin = gui.QgsMapLayerComboBox(self.frame_pts_layer)
        self.ComboBoxOrigin.setEnabled(False)
        self.ComboBoxOrigin.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ComboBoxOrigin.setFont(font)
        self.ComboBoxOrigin.setObjectName("ComboBoxOrigin")
        self.gridLayout_2.addWidget(self.ComboBoxOrigin, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_pts_layer)
        self.label.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_method = QtWidgets.QComboBox(OsrmBatchRouteDialog)
        self.comboBox_method.setGeometry(QtCore.QRect(30, 40, 391, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox_method.setFont(font)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.line_3 = QtWidgets.QFrame(OsrmBatchRouteDialog)
        self.line_3.setGeometry(QtCore.QRect(10, 70, 431, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.splitter.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButton_about.raise_()
        self.close_button_box.raise_()
        self.label_subtitle.raise_()
        self.frame_pts_layer.raise_()
        self.FieldOriginX.raise_()
        self.FieldOriginY.raise_()
        self.FieldDestinationX.raise_()
        self.FieldDestinationY.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.comboBox_method.raise_()
        self.line_3.raise_()

        self.retranslateUi(OsrmBatchRouteDialog)
        self.close_button_box.accepted.connect(OsrmBatchRouteDialog.accept)
        self.close_button_box.rejected.connect(OsrmBatchRouteDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OsrmBatchRouteDialog)

    def retranslateUi(self, OsrmBatchRouteDialog):
        _translate = QtCore.QCoreApplication.translate
        OsrmBatchRouteDialog.setWindowTitle(_translate("OsrmBatchRouteDialog", "OSRM"))
        self.label_subtitle.setToolTip(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_subtitle.setText(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\">Batch OSRM viaroute</p></body></html>"))
        self.pushButtonRun.setText(_translate("OsrmBatchRouteDialog", "Compute and save the result"))
        self.pushButtonReverse.setText(_translate("OsrmBatchRouteDialog", "Reverse O/D"))
        self.check_add_layer.setText(_translate("OsrmBatchRouteDialog", "Add the result to the canvas"))
        self.pushButton_about.setText(_translate("OsrmBatchRouteDialog", "About.."))
        self.label_6.setText(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\">Origins coords</p></body></html>"))
        self.label_7.setText(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\">Destinations coords</p></body></html>"))
        self.label_8.setText(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.label_9.setText(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\">Y</p></body></html>"))
        self.label_5.setText(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\">Csv file :</p></body></html>"))
        self.pushButtonBrowse.setText(_translate("OsrmBatchRouteDialog", "Browse"))
        self.label_11.setText(_translate("OsrmBatchRouteDialog", "Output file"))
        self.label_10.setText(_translate("OsrmBatchRouteDialog", "Host"))
        self.lineEdit_profileName.setText(_translate("OsrmBatchRouteDialog", "v1/driving"))
        self.label_3.setText(_translate("OsrmBatchRouteDialog", "Profile"))
        self.comboBox_host.setItemText(0, _translate("OsrmBatchRouteDialog", "http://127.0.0.1:5000/"))
        self.comboBox_host.setItemText(1, _translate("OsrmBatchRouteDialog", "http://router.project-osrm.org/"))
        self.comboBox_host.setItemText(2, _translate("OsrmBatchRouteDialog", "Add an url..."))
        self.label_2.setText(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\">Destination layer</p></body></html>"))
        self.label.setText(_translate("OsrmBatchRouteDialog", "<html><head/><body><p align=\"center\">Origin layer</p></body></html>"))
        self.comboBox_method.setItemText(0, _translate("OsrmBatchRouteDialog", "Choose a method..."))
        self.comboBox_method.setItemText(1, _translate("OsrmBatchRouteDialog", "Routes between two layers of points"))
        self.comboBox_method.setItemText(2, _translate("OsrmBatchRouteDialog", "Routes from a .csv file of paired origins-destinations"))

from qgis import gui
