# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'osrm_tsp_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OsrmTspDialog(object):
    def setupUi(self, OsrmTspDialog):
        OsrmTspDialog.setObjectName("OsrmTspDialog")
        OsrmTspDialog.resize(505, 315)
        self.pushButton_about = QtWidgets.QPushButton(OsrmTspDialog)
        self.pushButton_about.setGeometry(QtCore.QRect(11, 280, 85, 27))
        self.pushButton_about.setObjectName("pushButton_about")
        self.close_button_box = QtWidgets.QDialogButtonBox(OsrmTspDialog)
        self.close_button_box.setGeometry(QtCore.QRect(390, 280, 91, 27))
        self.close_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.close_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.close_button_box.setObjectName("close_button_box")
        self.pushButton_display = QtWidgets.QPushButton(OsrmTspDialog)
        self.pushButton_display.setGeometry(QtCore.QRect(180, 250, 144, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_display.setFont(font)
        self.pushButton_display.setObjectName("pushButton_display")
        self.layoutWidget = QtWidgets.QWidget(OsrmTspDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 461, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_layer = gui.QgsMapLayerComboBox(self.layoutWidget)
        self.comboBox_layer.setObjectName("comboBox_layer")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_layer)
        self.checkBox_selec_features = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setItalic(True)
        self.checkBox_selec_features.setFont(font)
        self.checkBox_selec_features.setObjectName("checkBox_selec_features")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_selec_features)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_host = QtWidgets.QLabel(self.layoutWidget)
        self.label_host.setObjectName("label_host")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_host)
        self.lineEdit_host = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_host.setFont(font)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_host)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_profileName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_profileName.setFont(font)
        self.lineEdit_profileName.setObjectName("lineEdit_profileName")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_profileName)
        self.checkBox_instructions = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_instructions.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setItalic(False)
        self.checkBox_instructions.setFont(font)
        self.checkBox_instructions.setObjectName("checkBox_instructions")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.checkBox_instructions)
        self.label_subtitle = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_subtitle.setFont(font)
        self.label_subtitle.setObjectName("label_subtitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_subtitle)
        self.pushButton_clear = QtWidgets.QPushButton(OsrmTspDialog)
        self.pushButton_clear.setGeometry(QtCore.QRect(160, 220, 181, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.retranslateUi(OsrmTspDialog)
        self.close_button_box.accepted.connect(OsrmTspDialog.accept)
        self.close_button_box.rejected.connect(OsrmTspDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OsrmTspDialog)

    def retranslateUi(self, OsrmTspDialog):
        _translate = QtCore.QCoreApplication.translate
        OsrmTspDialog.setWindowTitle(_translate("OsrmTspDialog", "OSRM"))
        self.pushButton_about.setText(_translate("OsrmTspDialog", "About.."))
        self.pushButton_display.setText(_translate("OsrmTspDialog", "Display the result"))
        self.label_3.setText(_translate("OsrmTspDialog", "Source point layer"))
        self.checkBox_selec_features.setText(_translate("OsrmTspDialog", "Only between selected features"))
        self.label_host.setText(_translate("OsrmTspDialog", "Host"))
        self.lineEdit_host.setText(_translate("OsrmTspDialog", "http://127.0.0.1:5000/"))
        self.label_4.setText(_translate("OsrmTspDialog", "Profile"))
        self.lineEdit_profileName.setText(_translate("OsrmTspDialog", "v1/driving"))
        self.checkBox_instructions.setText(_translate("OsrmTspDialog", "Display routing instructions"))
        self.label_subtitle.setToolTip(_translate("OsrmTspDialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_subtitle.setText(_translate("OsrmTspDialog", "<html><head/><body><p align=\"center\">Solve the Traveling Salesman Problem with OSRM</p></body></html>"))
        self.pushButton_clear.setText(_translate("OsrmTspDialog", "Clear previous results"))

from qgis import gui
